language: cpp
dist: trusty
sudo: false
matrix:
    include:
        -   os: linux
            compiler: gcc
            addons: &gcc6
                apt:
                    sources: ['ubuntu-toolchain-r-test']
                    packages:
                        - 'g++-7'
                        - 'libsdl2-dev'
            env: C='gcc-7' CXX='g++-7'
        -   os: linux
            compiler: clang
            addons: &clang40
                apt:
                    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
                    packages:
                        - 'libstdc++-7-dev'
                        - 'clang-5.0'
                        - 'libsdl2-dev'
            env: C='clang-5.0' CXX='clang++-5.0'
before_script:
    - export C=${C}
    - export CXX=${CXX}
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -Wdev ..
    - cmake --build .
script:
    - cd ${TRAVIS_BUILD_DIR}/build
    - ./sdlwrapper-test
